STRINGS = {
    "ar": {
        "welcome": "🎯 *مرحباً بك في Zone Luck!*\n\n👤 اسمك: {name}\n💰 رصيدك: ${balance:.2f}\n\nاختر من القائمة أدناه:",
        "main_menu_title": "🎯 *القائمة الرئيسية*\n\n💰 رصيدك: ${balance:.2f}",
        "btn_wallet": "💰 محفظتي",
        "btn_matches": "⚽ الرهانات",
        "btn_lottery": "🎟 اليانصيب",
        "btn_referral": "👥 الإحالة",
        "btn_stats": "📊 رصيدي وسجلاتي",
        "btn_admin": "🔧 لوحة الأدمن",
        "btn_back": "🔙 الرئيسية",
        "btn_back_short": "🔙 رجوع",
        "btn_language": "🌐 اللغة / Language",

        "wallet_title": "💰 *محفظتك*\n\nالرصيد الحالي: *${balance:.2f}*\n\nالحد الأدنى للإيداع: $5\nالحد الأدنى للسحب: $10",
        "btn_deposit": "📥 إيداع",
        "btn_withdraw": "📤 سحب",

        "deposit_title": "📥 *طلب إيداع*\n\nاختر الشبكة:",
        "deposit_no_address": "⚠️ عنوان المحفظة غير متوفر حالياً. تواصل مع الأدمن.",
        "deposit_instructions": "📥 *إيداع عبر USDT {network}*\n\nأرسل USDT إلى هذا العنوان:\n`{address}`\n\n⚠️ الحد الأدنى: *$5*\n\nبعد التحويل، أرسل رقم المعاملة (Transaction Hash) أو صورة الإثبات:",
        "deposit_verifying": "⏳ جاري التحقق من المعاملة...",
        "deposit_success": "✅ *تم التحقق من الإيداع تلقائياً!*\n\nالمبلغ: *${amount:.2f} USDT*\nتم إضافته لرصيدك.",
        "deposit_pending": "⏳ *تم استلام طلب الإيداع*\n\nسيتم مراجعته من قبل الأدمن قريباً.",
        "deposit_invalid_hash": "❌ لم يتم العثور على المعاملة أو المبلغ أقل من $5. تأكد من الهاش وأعد المحاولة.",

        "withdraw_start": "📤 *طلب سحب*\n\nالرصيد المتاح: *${balance:.2f}*\n\nأرسل عنوان محفظة USDT (TRC-20 أو BEP-20):",
        "withdraw_enter_amount": "💵 *عنوان محفظتك:*\n`{address}`\n\nالرصيد المتاح: *${balance:.2f}*\n\nأدخل المبلغ المراد سحبه (الحد الأدنى $10):",
        "withdraw_insufficient": "❌ رصيدك غير كافٍ للسحب.\nرصيدك: ${balance:.2f}",
        "withdraw_min_error": "❌ الحد الأدنى للسحب هو $10.",
        "withdraw_success": "✅ *تم تقديم طلب السحب*\n\nالمبلغ: *${amount:.2f}*\nسيتم المراجعة والتحويل خلال 24 ساعة.",
        "withdraw_invalid_amount": "❌ مبلغ غير صحيح. أدخل رقماً.",

        "matches_title": "⚽ *قسم الرهانات*\n\nاختر فئة المباريات:",
        "btn_today": "📅 مباريات اليوم",
        "btn_week": "📆 مباريات الأسبوع",
        "btn_all": "🌍 كل المباريات",
        "no_matches": "ℹ️ لا توجد مباريات متاحة حالياً.",
        "matches_list_title": "⚽ *مباريات {category}*\n\nاختر مباراة للمراهنة:",
        "match_not_found": "❌ المباراة غير موجودة.",
        "choose_bet_type": "⚽ *{home} vs {away}*\n🗓 {time}\n\nاختر نوع الرهان:",
        "insufficient_balance": "❌ رصيدك غير كافٍ.\nرسوم الرهان: ${fee}\nرصيدك: ${balance:.2f}",
        "bet_prompt": "{name}\n💵 رسوم الدخول: ${fee}\n🏆 الجائزة عند الفوز: ${payout}\n\n{prompt}",
        "bet_registered": "✅ *تم تسجيل رهانك!*\n\n⚽ المباراة: {match}\n{bet_name}\n🎯 توقعك: {prediction}\n💵 رسوم الدخول: ${fee}\n🏆 الجائزة المحتملة: ${payout}\n\nسيتم تسوية الرهان بعد انتهاء المباراة.",
        "bet_error": "❌ حدث خطأ. حاول مجدداً.",
        "cancelled": "❌ تم الإلغاء.",
        "invalid_bet_type": "❌ نوع رهان غير صحيح.",
        "category_today": "اليوم",
        "category_week": "الأسبوع",
        "category_all": "الكل",

        "bet_correct_score_name": "⚽ نتيجة صحيحة",
        "bet_correct_score_prompt": "أدخل توقعك للنتيجة النهائية (مثال: 2-1):",
        "bet_yellow_card_name": "🟡 بطاقة صفراء",
        "bet_yellow_card_prompt": "أدخل اسم اللاعب الذي ستصله بطاقة صفراء:",
        "bet_red_card_name": "🔴 بطاقة حمراء",
        "bet_red_card_prompt": "أدخل اسم اللاعب الذي ستصله بطاقة حمراء:",
        "bet_penalty_name": "⚡ ركلات الترجيح",
        "bet_penalty_prompt": "أدخل نتيجة ركلات الترجيح (مثال: 4-3):",

        "lottery_title": "🎟 *يانصيب Zone Luck*\n\n💵 سعر التذكرة: $5\n🏆 الجوائز:\n  🥇 الأولى: $100\n  🥈 الثانية: $200\n  🥉 الثالثة: $500\n\n💰 رصيدك: ${balance:.2f}\n\n",
        "lottery_active_tickets": "🎫 *تذاكرك النشطة:*\n",
        "lottery_more_tickets": "  ... و{count} أخرى\n",
        "lottery_won_tickets": "\n🏆 *تذاكر فائزة:*\n",
        "btn_buy_ticket": "🎟 شراء تذكرة ($5)",
        "lottery_insufficient": "❌ رصيدك غير كافٍ لشراء تذكرة.\nرصيدك: ${balance:.2f}\nسعر التذكرة: $5",
        "lottery_confirm_msg": "🎟 *شراء تذكرة يانصيب*\n\nالسعر: $5\nرصيدك بعد الشراء: ${after:.2f}\n\nهل تريد تأكيد الشراء؟",
        "btn_confirm": "✅ تأكيد",
        "btn_cancel": "❌ إلغاء",
        "lottery_bought": "✅ *تم شراء التذكرة بنجاح!*\n\n🎟 رقم تذكرتك: `{ticket}`\nاحتفظ بهذا الرقم — سيُعلن عن النتائج قريباً!\n\nبالتوفيق! 🍀",
        "lottery_insufficient_short": "❌ رصيدك غير كافٍ.",

        "referral_title": "👥 *نظام الإحالة*\n\n🔗 رابط الإحالة الخاص بك:\n`{link}`\n\n👤 عدد المدعوين: {count}\n✅ مكافآت مكتسبة: {rewarded} × $0.50 = ${earned:.2f}\n\n",
        "referral_invited_by": "👆 دعاك: {name}\n\n",
        "referral_downline": "👇 *المدعوون منك:*\n",
        "referral_more": "  ... و{count} آخرين\n",

        "stats_title": "📊 *إحصائياتك*\n\n",
        "stats_balance": "💰 الرصيد: ${balance:.2f}\n",
        "stats_tickets": "🎟 تذاكر اليانصيب: {count}\n\n",
        "stats_bets": "⚽ *آخر الرهانات:*\n",
        "stats_deposits": "📥 *آخر الإيداعات:*\n",
        "stats_withdrawals": "📤 *آخر السحوبات:*\n",
        "user_not_found": "❌ لم يتم العثور على حسابك.",

        "choose_language": "🌐 اختر لغتك:\n\nChoose your language:",
        "language_set": "✅ تم تغيير اللغة إلى العربية.",
    },

    "en": {
        "welcome": "🎯 *Welcome to Zone Luck!*\n\n👤 Name: {name}\n💰 Balance: ${balance:.2f}\n\nChoose from the menu below:",
        "main_menu_title": "🎯 *Main Menu*\n\n💰 Balance: ${balance:.2f}",
        "btn_wallet": "💰 My Wallet",
        "btn_matches": "⚽ Betting",
        "btn_lottery": "🎟 Lottery",
        "btn_referral": "👥 Referral",
        "btn_stats": "📊 My Stats",
        "btn_admin": "🔧 Admin Panel",
        "btn_back": "🔙 Main Menu",
        "btn_back_short": "🔙 Back",
        "btn_language": "🌐 اللغة / Language",

        "wallet_title": "💰 *Your Wallet*\n\nCurrent Balance: *${balance:.2f}*\n\nMinimum Deposit: $5\nMinimum Withdrawal: $10",
        "btn_deposit": "📥 Deposit",
        "btn_withdraw": "📤 Withdraw",

        "deposit_title": "📥 *Deposit Request*\n\nChoose network:",
        "deposit_no_address": "⚠️ Wallet address not available. Contact admin.",
        "deposit_instructions": "📥 *Deposit via USDT {network}*\n\nSend USDT to this address:\n`{address}`\n\n⚠️ Minimum: *$5*\n\nAfter transfer, send the Transaction Hash or proof screenshot:",
        "deposit_verifying": "⏳ Verifying transaction...",
        "deposit_success": "✅ *Deposit verified automatically!*\n\nAmount: *${amount:.2f} USDT*\nAdded to your balance.",
        "deposit_pending": "⏳ *Deposit request received*\n\nWill be reviewed by admin shortly.",
        "deposit_invalid_hash": "❌ Transaction not found or amount below $5. Check the hash and try again.",

        "withdraw_start": "📤 *Withdrawal Request*\n\nAvailable Balance: *${balance:.2f}*\n\nSend your USDT wallet address (TRC-20 or BEP-20):",
        "withdraw_enter_amount": "💵 *Your wallet address:*\n`{address}`\n\nAvailable Balance: *${balance:.2f}*\n\nEnter amount to withdraw (minimum $10):",
        "withdraw_insufficient": "❌ Insufficient balance.\nYour balance: ${balance:.2f}",
        "withdraw_min_error": "❌ Minimum withdrawal is $10.",
        "withdraw_success": "✅ *Withdrawal request submitted*\n\nAmount: *${amount:.2f}*\nWill be processed within 24 hours.",
        "withdraw_invalid_amount": "❌ Invalid amount. Enter a number.",

        "matches_title": "⚽ *Betting Section*\n\nChoose match category:",
        "btn_today": "📅 Today's Matches",
        "btn_week": "📆 This Week",
        "btn_all": "🌍 All Matches",
        "no_matches": "ℹ️ No matches available right now.",
        "matches_list_title": "⚽ *{category} Matches*\n\nChoose a match to bet on:",
        "match_not_found": "❌ Match not found.",
        "choose_bet_type": "⚽ *{home} vs {away}*\n🗓 {time}\n\nChoose bet type:",
        "insufficient_balance": "❌ Insufficient balance.\nBet fee: ${fee}\nYour balance: ${balance:.2f}",
        "bet_prompt": "{name}\n💵 Entry fee: ${fee}\n🏆 Prize if won: ${payout}\n\n{prompt}",
        "bet_registered": "✅ *Bet placed!*\n\n⚽ Match: {match}\n{bet_name}\n🎯 Your prediction: {prediction}\n💵 Entry fee: ${fee}\n🏆 Potential prize: ${payout}\n\nBet will be settled after the match.",
        "bet_error": "❌ An error occurred. Try again.",
        "cancelled": "❌ Cancelled.",
        "invalid_bet_type": "❌ Invalid bet type.",
        "category_today": "Today",
        "category_week": "This Week",
        "category_all": "All",

        "bet_correct_score_name": "⚽ Correct Score",
        "bet_correct_score_prompt": "Enter your final score prediction (e.g. 2-1):",
        "bet_yellow_card_name": "🟡 Yellow Card",
        "bet_yellow_card_prompt": "Enter the player's name who will receive a yellow card:",
        "bet_red_card_name": "🔴 Red Card",
        "bet_red_card_prompt": "Enter the player's name who will receive a red card:",
        "bet_penalty_name": "⚡ Penalty Shootout",
        "bet_penalty_prompt": "Enter the penalty shootout result (e.g. 4-3):",

        "lottery_title": "🎟 *Zone Luck Lottery*\n\n💵 Ticket price: $5\n🏆 Prizes:\n  🥇 1st: $100\n  🥈 2nd: $200\n  🥉 3rd: $500\n\n💰 Your balance: ${balance:.2f}\n\n",
        "lottery_active_tickets": "🎫 *Your active tickets:*\n",
        "lottery_more_tickets": "  ... and {count} more\n",
        "lottery_won_tickets": "\n🏆 *Winning tickets:*\n",
        "btn_buy_ticket": "🎟 Buy Ticket ($5)",
        "lottery_insufficient": "❌ Insufficient balance.\nYour balance: ${balance:.2f}\nTicket price: $5",
        "lottery_confirm_msg": "🎟 *Buy Lottery Ticket*\n\nPrice: $5\nBalance after purchase: ${after:.2f}\n\nConfirm purchase?",
        "btn_confirm": "✅ Confirm",
        "btn_cancel": "❌ Cancel",
        "lottery_bought": "✅ *Ticket purchased successfully!*\n\n🎟 Your ticket number: `{ticket}`\nKeep this number — results will be announced soon!\n\nGood luck! 🍀",
        "lottery_insufficient_short": "❌ Insufficient balance.",

        "referral_title": "👥 *Referral System*\n\n🔗 Your referral link:\n`{link}`\n\n👤 Referrals: {count}\n✅ Earned rewards: {rewarded} × $0.50 = ${earned:.2f}\n\n",
        "referral_invited_by": "👆 Invited by: {name}\n\n",
        "referral_downline": "👇 *Your referrals:*\n",
        "referral_more": "  ... and {count} more\n",

        "stats_title": "📊 *Your Stats*\n\n",
        "stats_balance": "💰 Balance: ${balance:.2f}\n",
        "stats_tickets": "🎟 Lottery tickets: {count}\n\n",
        "stats_bets": "⚽ *Recent Bets:*\n",
        "stats_deposits": "📥 *Recent Deposits:*\n",
        "stats_withdrawals": "📤 *Recent Withdrawals:*\n",
        "user_not_found": "❌ Account not found.",

        "choose_language": "🌐 اختر لغتك:\n\nChoose your language:",
        "language_set": "✅ Language set to English.",
    },
}


def t(key: str, lang: str, **kwargs) -> str:
    text = STRINGS.get(lang, STRINGS["ar"]).get(key, STRINGS["ar"].get(key, key))
    if kwargs:
        try:
            return text.format(**kwargs)
        except Exception:
            return text
    return text
